[project]
name = "maestro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.6.4",
    "dotenv>=0.9.9",
    "proxmoxer>=2.2.0",
    "requests>=2.32.5",
]
